/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.jarsonmar.neptune.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ExitProp implements org.apache.thrift.TEnum {
  ALL(1),
  NORTH(2),
  SOUTH(3),
  EAST(4),
  WEST(5),
  UP(6),
  DOWN(7);

  private final int value;

  private ExitProp(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExitProp findByValue(int value) { 
    switch (value) {
      case 1:
        return ALL;
      case 2:
        return NORTH;
      case 3:
        return SOUTH;
      case 4:
        return EAST;
      case 5:
        return WEST;
      case 6:
        return UP;
      case 7:
        return DOWN;
      default:
        return null;
    }
  }
}
