/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.jarsonmar.neptune.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LocProp implements org.apache.thrift.TEnum {
  MOBS(1),
  PLRS(2),
  OBJS(3),
  EXIT(4),
  PROP(5),
  FLAG(6);

  private final int value;

  private LocProp(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LocProp findByValue(int value) { 
    switch (value) {
      case 1:
        return MOBS;
      case 2:
        return PLRS;
      case 3:
        return OBJS;
      case 4:
        return EXIT;
      case 5:
        return PROP;
      case 6:
        return FLAG;
      default:
        return null;
    }
  }
}
