/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.jarsonmar.neptune.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RequestType implements org.apache.thrift.TEnum {
  CREATE(1),
  READ(2),
  UPDATE(3),
  DELETE(4),
  LIST(5);

  private final int value;

  private RequestType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RequestType findByValue(int value) { 
    switch (value) {
      case 1:
        return CREATE;
      case 2:
        return READ;
      case 3:
        return UPDATE;
      case 4:
        return DELETE;
      case 5:
        return LIST;
      default:
        return null;
    }
  }
}
